#!/bin/sh

set -e

pxe_server_ip=$(ifconfig $INTERFACE | grep 'inet addr:' | cut -d: -f2 | awk '{print $1}')

echo Server IP: $pxe_server_ip

# Update discovery token, bootstrap with 3 nodes
# sed -i -e s,DISCOVERY_TOKEN,$(wget -qO- https://discovery.etcd.io/new?size=3),g /pxe/cloud-config.yml

# Fallback to default config if user dose not provide
[ ! -d /config/pxelinux.cfg ] && \
    echo "Use default configs" && cp -a /app/config/. /config

# Copy to tftp root
cp -R /config/pxelinux.cfg /app/tftp
chmod a+r /app/tftp/pxelinux.cfg/*

# Update pxelinux config to point real server ip
sed -i -e s/%\(server_ip\)s/$pxe_server_ip/ /app/tftp/pxelinux.cfg/*

# Start http server to host cloud.config
python3 -u /app/httpd.py /config $pxe_server_ip 80 &

# Download image
if [ ! -d /config/images ];then
    echo "Downloading CoreOS images"
    mkdir -p /config/images/633.1.0
    wget http://stable.release.core-os.net/amd64-usr/633.1.0/coreos_production_image.bin.bz2
    wget http://stable.release.core-os.net/amd64-usr/633.1.0/coreos_production_image.bin.bz2.sig
fi

# Host images
cd /config/images
python3 -u -m http.server 3000 &

# Start dnsmasq as dhcp proxy to $pxe_server_ip
dnsmasq \
    --dhcp-range=$pxe_server_ip,proxy \
    --dhcp-no-overrid \
    --dhcp-boot=pxelinux.0,pxeserver,$pxe_server_ip \
    --pxe-service=x86PC,"Install CoreOS",pxelinux \
    --enable-tftp \
    --tftp-root=/app/tftp \
    --user=root \
    --no-daemon

